version: '3'
services:
  angular:
    container_name: pickeat-api
    build: .
    ports:
        - 8089:4200
        - 49153:49153
    volumes:
      - .:/pickeat-api
    tty: true
    environment:
        - NODE_ENV=dev
    command: /bin/sh -c "npm install && ng serve"